spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity
    username: student
    password: 888337
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
